name: app-push-workflow

on:
    push:
        branches:
            - prod-stg

jobs:
    deploy:
        name: Deploye node js service to EC2
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the files
              uses: actions/checkout@v2

            - name: Deploy/copy code to api server
              uses: easingthemes/ssh-deploy@main
              env:
                SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
                REMOTE_HOST: ${{secrets.HOST_DNS}}
                REMOTE_USER: ${{secrets.USERNAME}}
                TARGET: ${{secrets.TARGET_DIR}}
